# Date for which meals should be recommended
dates:
  - 2022-09-12
  - 2022-09-13
  - 2022-09-14
  - 2022-09-15
  - 2022-09-16

# Rules to apply when deciding on a meal plan
# Entries should be names of elements of the Rules enum in src/rule.py
rules:
  - NOT_PASTA_TWICE_WITHIN_FIVE_DAYS
  - NOT_ROAST_ON_NON_SUNDAY
  - NOT_SAME_MEAL_WITHIN_SEVEN_DAYS
  - NOT_SAME_MEAT_ON_CONSECUTIVE_DAYS

# Meals to choose a meal plan from. Meals not in this list are not considered
# Entries should be names of meals as defined in the Meals enum in src/meal.py
meals:
  - Beef and Ale Stew
  - Chicken Fajitas
  - Chicken Taleggio
  - Chicken and Green Bean Vermicelli Noodles
  - Chilli Chicken Thighs with Cherry Tomatoes
  - Chilli con Carne
  - Lasagne
  - Pasta with Chicken and Sundried Tomatoes
  - Roast Beef
  - Roast Chicken
  - Roast Lamb
  - Roast Pork
  - Shephards Pie
  - Spaghetti Bolognese
  - Sticky Chinese Pork Belly

# NB: email_addresses are not currently in use in the project
email_addresses:
  - mealprepbot@gmail.com
  - testaddress@foo.bar
