# Date for which meals should be recommended
dates:
  - 2023-01-26

# Rules to apply when deciding on a meal plan
# Entries should be names of elements of the Rules enum in src/rule.py
rules:
  - NOT_PASTA_TWICE_WITHIN_FIVE_DAYS
  - NOT_ROAST_ON_NON_SUNDAY
  - NOT_SAME_MEAL_WITHIN_SEVEN_DAYS

# Meals to choose a meal plan from. Meals not in this list are not considered
# Entries should be names of meals as defined in the Meals enum in src/meal.py
meals:
  - Beef and Ale Stew
  - Burgers
  - Chicken Fajitas
  - Chicken Piccata
  - Chicken Soup
  - Chicken Taleggio
  - Chicken and Green Bean Vermicelli Noodles
  - Chicken and Leek Pie
  - Chilli Chicken Thighs with Cherry Tomatoes
  - Chilli con Carne
  - Lasagne
  - Lemon Leek Linguine
  - Parmesan Crust Baked Chicken
  - Pasta with Chicken and Sundried Tomatoes
  - Roast Beef
  - Roast Chicken
  - Roast Lamb
  - Roast Pork
  - Shepherds Pie
  - Spaghetti Bolognese
  - Sticky Chinese Pork Belly
  - Turkey Sweet Potato Shepherds Pie

# NB: email_addresses are not currently in use in the project
email_addresses:
  - mealprepbot@gmail.com
  - testaddress@foo.bar
