email_addresses:
  - mealprepbot@gmail.com
  - testaddress@foo.bar
dates:
  - 2022-02-05
  - 2022-02-06
  - 2022-02-08
rules:
  - NOT_PASTA_TWICE_WITHIN_FIVE_DAYS
  - NOT_SAME_MEAT_ON_CONSECUTIVE_DAYS
